In [87]:
import numpy as np
a= [1,2,3,4,5]
A= np.array([5,6,7,8,9,10])
print (a)
print (A)

[1, 2, 3, 4, 5]
[ 5  6  7  8  9 10]


In [8]:
import numpy as np
b =np.array([1,2,3,4,5,6,7,8,9])
x= b.reshape(3,3)
print (x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
x.shape

(3, 3)

In [24]:
np.zeros((4,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

np.arange(0,10,2)

In [23]:
A.shape

(6,)

In [22]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
J= np.eye(3)
print (J)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
K= np.dot(x,J)
print (K)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [26]:
sum_K = np.sum(K)
print(sum_K)

45.0


In [28]:
#sum along the rows(p) and columns respectively(q)
p= np.sum(K, axis=1)
q = np.sum(K, 0)
print (p)
print(q)
#not necessary to include "axis"

[ 6. 15. 24.]
[12. 15. 18.]


In [29]:
my_list = [1,2,3,4,5,6,7,8,9]
seclist = np.array([my_list])
print(seclist)

[[1 2 3 4 5 6 7 8 9]]


In [32]:
#notice the double parenthesis in my_ones1
my_ones = np.ones(5)
my_ones1 = np.ones((3,3))

print (my_ones1)
print (my_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [33]:
#linspace() function returns numbers evenly spaced over a specified interval
#linspace is quite different from arange(which takes the third argument as a step), instead it takes it as the number
#of datapoints to be created
lin_arr =np.linspace(1,3,15)
print (lin_arr)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.        ]


In [36]:
#generating an array of random numbers: we can use rand(), randn() or randint() functions
#random.rand():for generation of array of random numbers of the shape we pass to it from uniform distribution over o to 1
my_rand = np.random.rand(4)
my_rand1 = np.random.rand(3,2)

print (my_rand)
print (my_rand1)


[0.03024336 0.83301664 0.58293091 0.11137219]
[[0.87306132 0.81972671]
 [0.61185543 0.84513116]
 [0.39003142 0.16986353]]


In [37]:
#random.randn():for generation of random samples from standard, normal or guassian distribution centered around 0
my_randn = np.random.randn(5)
my_randn1 = np.random.randn(3,4)
print (my_randn)
print (my_randn1)
#the plot of the result gives us a normal distribution curve

[ 1.08509978 -0.26236786  0.26080692  0.23165442  0.2992924 ]
[[-0.74552572  1.0145701  -0.03247582 -0.44528673]
 [-0.01684638  0.35902755 -0.04001857 -0.16010307]
 [-0.34815327  0.1661404   0.03447171  1.31417105]]


In [48]:
#random.randint():for generation of an array of integers
R1= np.random.randint(10) #generates a random integer exclusive 10
R2= np.random.randint(3,15) #generates a random integer including 3 but excluding 15
R3= np.random.randint(2,20,7) #generates 7 random numbers including 2, but excluding 20
print (R1)
print (R2)
print (R3)

8
12
[15 19  6  2  8  4 16]


In [42]:
R3.max() #this gives the highest value in the array

18

In [50]:
R3.min()  #this gives the lowest value in the array

2

In [44]:
R3.argmax()  #this gives the index of the highest value in the array

6

In [49]:
R3.argmin()  #this gives the index of the minimum value in the array

3

In [51]:
R3[5]  #this gives us the value at index 5 of the array

4

In [52]:
R3[2:5] #this returns everything from index 2 to 5(exclusive)
R3[:4]  #this returns everything from index 0 to 4(exclusive)
R3[3:]  #this returns everything from index 3 to the end of the array


array([ 2,  8,  4, 16])

In [55]:
#to select from a 2d array, we can either use [][] or [,]
arr1 = np.array([[10,20,30], [40,50.60], [70,80,90]])
arr1[2][2]  # to select 90 from the array

90

In [65]:
new_arr = np.arange(1,15)
new_arr > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [67]:
bool_arr = (new_arr >10)
new_arr[bool_arr]

array([11, 12, 13, 14])

In [75]:
#instead, we could skip line 67 and just say:
new_arr[new_arr > 10]

array([], dtype=bool)

In [80]:
bool_arr = ((new_arr >6) & (new_arr <11))
new_arr[bool_arr]

array([], dtype=bool)

In [84]:
new_arr[0:3] = 50
print (new_arr)

[ True  True  True False False False False False False False  True  True
  True  True]


In [85]:
np.exp(new_arr)

array([2.719, 2.719, 2.719, 1.   , 1.   , 1.   , 1.   , 1.   , 1.   ,
       1.   , 2.719, 2.719, 2.719, 2.719], dtype=float16)

In [88]:
np.random.randint(3, size = 7)

array([1, 1, 1, 2, 0, 2, 1])

In [92]:
np.random.randint(2, 10, size = (3,2))

array([[6, 2],
       [8, 5],
       [6, 7]])

In [94]:
np.random.random(8)

array([0.30404958, 0.91691412, 0.4851805 , 0.66919778, 0.21763846,
       0.01163545, 0.47364491, 0.63198536])

In [97]:
#random.randn is also used to create a sample from a standard normal distribution(i.e. zero mean and unit variance)
print(np.random.randn(28).mean())
print(np.random.randn(49).std())

0.060980733982659914
1.0458445795098374


In [99]:
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [100]:
np.full((3,4), 8, dtype="float")

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [112]:
T = np.random.randint(5, size=(4,3))
T

array([[3, 1, 4],
       [4, 3, 3],
       [4, 2, 2],
       [0, 2, 0]])

In [113]:
T.ravel()   #to ravel it row wise

array([3, 1, 4, 4, 3, 3, 4, 2, 2, 0, 2, 0])

In [114]:
T.ravel(order= "F")  #in order to ravel it column wise

array([3, 4, 4, 0, 1, 3, 2, 2, 4, 3, 2, 0])

In [115]:
T.reshape(-1, 4)  #once we pass -1 numpy figures out to arrange it

array([[3, 1, 4, 4],
       [3, 3, 4, 2],
       [2, 0, 2, 0]])

In [116]:
T.transpose()

array([[3, 4, 4, 0],
       [1, 3, 2, 2],
       [4, 3, 2, 0]])

In [117]:
np.vsplit(T, 2)

[array([[3, 1, 4],
        [4, 3, 3]]),
 array([[4, 2, 2],
        [0, 2, 0]])]

In [118]:
#to access a particular sub-array after splitting
np.vsplit(T, 2)[0]

array([[3, 1, 4],
       [4, 3, 3]])

In [122]:
#instead of vertically, Hsplit works horizontally
w = np.random.randint(5, size= (1,8))
np.hsplit(w, 2)

[array([[2, 3, 2, 0]]), array([[1, 0, 3, 1]])]

In [123]:
np.hsplit(T, 3)[0]

array([[3],
       [4],
       [4],
       [0]])

In [124]:
#we can alsso concatenate matrices
a= np.array([1,2,3,4])
b= np.array([2,2,2])
np.concatenate((a,b))

array([1, 2, 3, 4, 2, 2, 2])

In [125]:
a= np.array([1,2,3,4])
b= np.array([2,2,2,2])
np.concatenate((a.reshape(-1,1),b.reshape(-1,1)), axis = 1)

array([[1, 2],
       [2, 2],
       [3, 2],
       [4, 2]])

In [126]:
a= np.random.randint(5, size = (2,2,2))
b= np.random.randint(5, size=(2,2,2))
c= np.random.randint(5, size=(2,2,2))
np.vstack((a,b,c))  #this helps to stack arrays vertically(rows on top of each other)

array([[[0, 2],
        [3, 3]],

       [[3, 0],
        [2, 1]],

       [[3, 2],
        [0, 3]],

       [[3, 3],
        [2, 0]],

       [[1, 0],
        [4, 2]],

       [[3, 4],
        [3, 0]]])

In [127]:
#Hstacks just like vstacks works horizontally
a= np.array([1,2,3,4]).reshape(-1,1)
b= np.array([2,2,2,2]).reshape(-1,1)
c = np.array([0,1,5,6]).reshape(-1,1)
np.hstack((a,b,c))

array([[1, 2, 0],
       [2, 2, 1],
       [3, 2, 5],
       [4, 2, 6]])

In [3]:
import numpy as np
W = np.random.randint(7, size = (3,3))
np.linalg.det(W)

-2.0

In [5]:
np.linalg.inv(W)

array([[ 0.5,  0. ,  0. ],
       [-1.5, -0. ,  1. ],
       [-0.5,  1. , -1. ]])

In [6]:
np.linalg.eig(W)

(array([-0.61803399,  1.61803399,  2.        ]),
 array([[ 0.        ,  0.        ,  0.07647191],
        [ 0.52573111, -0.85065081,  0.84119102],
        [-0.85065081, -0.52573111,  0.53530338]]))

In [7]:
L = ([[3,4],[6,2]])
P = ([[7,8],[9,1]])
np.matmul(L,P)

array([[57, 28],
       [60, 50]])